services:
  java_app:
    container_name: java_app
    image: 'java_app:1.0.0'
    build: .
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    restart: always

  postgres:
    container_name: postgres_db
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=crud-db'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
